version: '3.0'

services:
  postgres:
    container_name: ${CONTAINER_PREFIX}_postgres
    image: postgres
    restart: on-failure
    build:
      context: ./docker/postgres/postgis
    ports:
      - ${DB_PORT:-5881}:${DB_PORT:-5881}
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_TEST}
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_USER: ${PG_USER}
      TZ: 'Europe/Moscow'
      PGTZ: 'Europe/Moscow'
    networks:
      - backend

networks:
  backend:
    driver: bridge
